name: Mirror to Public Repository

on:
  push:
    branches: [ main, develop ]  # Mirror main and develop branches
  release:
    types: [ published ]  # Also mirror on releases

jobs:
  mirror:
    runs-on: ubuntu-latest
    name: Mirror to SiteDesigner-public
    
    steps:
      - name: Checkout private repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history for proper mirroring
          
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
      - name: Mirror to public repository
        env:
          PUBLIC_REPO_URL: https://${{ secrets.PUBLIC_TOKEN }}@github.com/Waldeezy13/SiteDesigner-public.git
        run: |
          # Add public repository as remote
          git remote add public "$PUBLIC_REPO_URL"
          
          # Push all branches with force-with-lease for safety
          git push public --all --force-with-lease
          
          # Push all tags
          git push public --tags --force-with-lease
          
      - name: Verify mirror success
        run: |
          echo "? Successfully mirrored SiteDesigner .NET 8 AutoCAD add-in to public repository"
          echo "?? Public repository: https://github.com/Waldeezy13/SiteDesigner-public"